namespace CauldronModels;

public enum IG_VERTEX_USAGE {
    IG_VERTEX_USAGE_POSITION = 0,
    IG_VERTEX_USAGE_NORMAL = 1,
    IG_VERTEX_USAGE_TANGENT = 2,
    IG_VERTEX_USAGE_BINORMAL = 3,
    IG_VERTEX_USAGE_COLOR = 4,
    IG_VERTEX_USAGE_TEXCOORD = 5,
    IG_VERTEX_USAGE_BLENDWEIGHTS = 6,
    IG_VERTEX_USAGE_UNUSED_0 = 7,
    IG_VERTEX_USAGE_BLENDINDICES = 8,
    IG_VERTEX_USAGE_FOGCOORD = 9,
    IG_VERTEX_USAGE_PSIZE = 10,
}