namespace igLibrary.Gen.MetaEnum;

public enum IG_VERTEX_USAGE
{
	IG_VERTEX_USAGE_POSITION,
	IG_VERTEX_USAGE_NORMAL,
	IG_VERTEX_USAGE_TANGENT,
	IG_VERTEX_USAGE_BINORMAL,
	IG_VERTEX_USAGE_COLOR,
	IG_VERTEX_USAGE_TEXCOORD,
	IG_VERTEX_USAGE_BLENDWEIGHTS,
	IG_VERTEX_USAGE_UNUSED_0,
	IG_VERTEX_USAGE_BLENDINDICES,
	IG_VERTEX_USAGE_FOGCOORD,
	IG_VERTEX_USAGE_PSIZE
}
