namespace igLibrary.Gen.MetaEnum;

public enum igGraphicsMaterialAnimationTimeSource
{
	kGraphicsMaterialAnimationTimeSourceTransformed,
	kGraphicsMaterialAnimationTimeSourceGlobal,
	kGraphicsMaterialAnimationTimeSourceRandom
}
